services:
  jenkins:
    #image: jenkins/jenkins:lts
    build:
      context: ./JenkinsWithDocker
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home:lts
    restart: always

